name: Ansible Playbook
on:
  push:
    branches:
      - main

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: sudo apt-get install ansible -y

      - name: Run Playbook
        run: ansible-playbook -i ansible/inventories/aws/hosts ansible/playbooks/webserver.yml
